// Example locale file for English, give this to your locale team to translate

export const AG_GRID_LOCALE_FA = {
  // Set Filter
  selectAll: "(انتخاب همه)",
  selectAllSearchResults: "(انتخاب همه نتایج جستجو)",
  addCurrentSelectionToFilter: "افزودن انتخاب فعلی به فیلتر",
  searchOoo: "جستجو...",
  blanks: "(خالی‌ها)",
  noMatches: "هیچ موردی یافت نشد",

  // Number Filter & Text Filter
  filterOoo: "فیلتر...",
  equals: "برابر است با",
  notEqual: "برابر نیست با",
  blank: "خالی",
  notBlank: "خالی نیست",
  empty: "یکی را انتخاب کنید",

  // Number Filter
  lessThan: "کمتر از",
  greaterThan: "بیشتر از",
  lessThanOrEqual: "کمتر یا مساوی",
  greaterThanOrEqual: "بیشتر یا مساوی",
  inRange: "بین",
  inRangeStart: "از",
  inRangeEnd: "تا",

  // Text Filter
  contains: "شامل",
  notContains: "شامل نمی‌شود",
  startsWith: "شروع می‌شود با",
  endsWith: "پایان می‌یابد با",

  // Date Filter
  dateFormatOoo: "yyyy-mm-dd",
  before: "قبل از",
  after: "بعد از",

  // Filter Conditions
  andCondition: "و",
  orCondition: "یا",

  // Filter Buttons
  applyFilter: "اعمال",
  resetFilter: "بازنشانی",
  clearFilter: "پاک کردن",
  cancelFilter: "لغو",

  // Filter Titles
  textFilter: "فیلتر متن",
  numberFilter: "فیلتر عدد",
  dateFilter: "فیلتر تاریخ",
  setFilter: "تنظیم فیلتر",

  // Group Column Filter
  groupFilterSelect: "انتخاب فیلد:",

  // Advanced Filter
  advancedFilterContains: "شامل",
  advancedFilterNotContains: "شامل نمی‌شود",
  advancedFilterTextEquals: "برابر است با",
  advancedFilterTextNotEqual: "برابر نیست با",
  advancedFilterStartsWith: "شروع می‌شود با",
  advancedFilterEndsWith: "پایان می‌یابد با",
  advancedFilterBlank: "خالی است",
  advancedFilterNotBlank: "خالی نیست",
  advancedFilterEquals: "=",
  advancedFilterNotEqual: "!=",
  advancedFilterGreaterThan: ">",
  advancedFilterGreaterThanOrEqual: ">=",
  advancedFilterLessThan: "<",
  advancedFilterLessThanOrEqual: "<=",
  advancedFilterTrue: "صحیح است",
  advancedFilterFalse: "غلط است",
  advancedFilterAnd: "و",
  advancedFilterOr: "یا",
  advancedFilterApply: "اعمال",
  advancedFilterBuilder: "سازنده",
  advancedFilterValidationMissingColumn: "ستون گم شده است",
  advancedFilterValidationMissingOption: "گزینه گم شده است",
  advancedFilterValidationMissingValue: "مقدار گم شده است",
  advancedFilterValidationInvalidColumn: "ستون یافت نشد",
  advancedFilterValidationInvalidOption: "گزینه یافت نشد",
  advancedFilterValidationMissingQuote:
    "مقدار یک نقل قول پایانی را از دست داده است",
  advancedFilterValidationNotANumber: "مقدار یک عدد نیست",
  advancedFilterValidationInvalidDate: "مقدار یک تاریخ معتبر نیست",
  advancedFilterValidationMissingCondition: "شرط گم شده است",
  advancedFilterValidationJoinOperatorMismatch:
    "عملگرهای اتصال درون یک شرط باید یکسان باشند",
  advancedFilterValidationInvalidJoinOperator: "عملگر اتصال یافت نشد",
  advancedFilterValidationMissingEndBracket: "پرانتز پایانی گم شده است",
  advancedFilterValidationExtraEndBracket: "پرانتزهای پایانی زیادی وجود دارد",
  advancedFilterValidationMessage:
    "عبارت یک خطا دارد. ${variable} - ${variable}.",
  advancedFilterValidationMessageAtEnd:
    "عبارت یک خطا دارد. ${variable} در انتهای عبارت.",
  advancedFilterBuilderTitle: "فیلتر پیشرفته",
  advancedFilterBuilderApply: "اعمال",
  advancedFilterBuilderCancel: "لغو",
  advancedFilterBuilderAddButtonTooltip: "افزودن فیلتر یا گروه",
  advancedFilterBuilderRemoveButtonTooltip: "حذف",
  advancedFilterBuilderMoveUpButtonTooltip: "انتقال به بالا",
  advancedFilterBuilderMoveDownButtonTooltip: "انتقال به پایین",
  advancedFilterBuilderAddJoin: "افزودن گروه",

  advancedFilterBuilderAddCondition: "افزودن فیلتر",
  advancedFilterBuilderSelectColumn: "انتخاب یک ستون",
  advancedFilterBuilderSelectOption: "انتخاب یک گزینه",
  advancedFilterBuilderEnterValue: "وارد کردن یک مقدار...",
  advancedFilterBuilderValidationAlreadyApplied:
    "فیلتر فعلی قبلا اعمال شده است.",
  advancedFilterBuilderValidationIncomplete: "همه شرایط کامل نیستند.",
  advancedFilterBuilderValidationSelectColumn: "باید یک ستون انتخاب کنید.",
  advancedFilterBuilderValidationSelectOption: "باید یک گزینه انتخاب کنید.",
  advancedFilterBuilderValidationEnterValue: "باید یک مقدار وارد کنید.",

  // Side Bar
  columns: "ستون‌ها",
  filters: "فیلترها",

  // columns tool panel
  pivotMode: "حالت Pivot",
  groups: "گروه‌های ردیف",
  rowGroupColumnsEmptyMessage: "برای تنظیم گروه‌های ردیف، اینجا بکشید",
  values: "مقادیر",
  valueColumnsEmptyMessage: "برای aggregate، اینجا بکشید",
  pivots: "برچسب‌های ستون",
  pivotColumnsEmptyMessage: "برای تنظیم برچسب‌های ستون، اینجا بکشید",

  // Header of the Default Group Column
  group: "گروه",

  // Row Drag
  rowDragRow: "ردیف",
  rowDragRows: "ردیف‌ها",

  // Other
  loadingOoo: "در حال بارگذاری...",
  loadingError: "خطا",
  noRowsToShow: "ردیفی برای نمایش وجود ندارد",
  enabled: "فعال",

  // Menu
  pinColumn: "سنجاق کردن ستون",
  pinLeft: "سنجاق کردن به چپ",
  pinRight: "سنجاق کردن به راست",
  noPin: "بدون سنجاق",
  valueAggregation: "تجمع مقدار",
  noAggregation: "بدون تجمع",
  autosizeThiscolumn: "Autosize این ستون",
  autosizeAllColumns: "Autosize همه ستون‌ها",
  groupBy: "گروه‌بندی بر اساس",
  ungroupBy: "حذف گروه‌بندی بر اساس",
  ungroupAll: "حذف همه گروه‌بندی‌ها",
  addToValues: "افزودن ${variable} به مقادیر",
  removeFromValues: "حذف ${variable} از مقادیر",
  addToLabels: "افزودن ${variable} به برچسب‌ها",
  removeFromLabels: "حذف ${variable} از برچسب‌ها",
  resetColumns: "بازنشانی ستون‌ها",
  expandAll: "گسترش همه گروه‌های ردیف",
  collapseAll: "بستن همه گروه‌های ردیف",
  copy: "کپی",
  ctrlC: "Ctrl+C",
  ctrlX: "Ctrl+X",
  copyWithHeaders: "کپی با سربرگ‌ها",
  copyWithGroupHeaders: "کپی با سربرگ‌های گروه",
  cut: "برش",
  paste: "چسباندن",
  ctrlV: "Ctrl+V",
  export: "صادر کردن",
  csvExport: "صادر کردن به CSV",
  excelExport: "صادر کردن به Excel",

  // Enterprise Menu Aggregation and Status Bar
  sum: "جمع",
  first: "اولین",
  last: "آخرین",
  min: "کمینه",
  max: "بیشینه",
  none: "هیچ",
  count: "تعداد",
  avg: "میانگین",
  filteredRows: "ردیف‌های فیلتر شده",
  selectedRows: "ردیف‌های انتخاب شده",
  totalRows: "کل ردیف‌ها",
  totalAndFilteredRows: "ردیف‌ها",
  more: "بیشتر",
  to: "به",
  of: "از",
  page: "صفحه",
  pageLastRowUnknown: "?",
  nextPage: "صفحه بعد",
  lastPage: "صفحه آخر",
  firstPage: "صفحه اول",
  previousPage: "صفحه قبل",
  pageSizeSelectorLabel: "اندازه صفحه:",

  // Pivoting
  pivotColumnGroupTotals: "مجموع",

  // Enterprise Menu (Charts)
  pivotChartAndPivotMode: "نمودار Pivot & حالت Pivot",
  pivotChart: "نمودار Pivot",
  chartRange: "محدوده نمودار",

  columnChart: "ستون",
  groupedColumn: "گروه‌بندی شده",
  stackedColumn: "روی هم رفته",
  normalizedColumn: "100% روی هم رفته",

  barChart: "میله‌ای",
  groupedBar: "گروه‌بندی شده",
  stackedBar: "روی هم رفته",
  normalizedBar: "100% روی هم رفته",

  pieChart: "دایره‌ای",
  pie: "دایره‌ای",
  doughnut: "دونات",

  line: "خط",

  xyChart: "X Y (پراکندگی)",
  scatter: "پراکندگی",
  bubble: "حباب",

  areaChart: "منطقه",
  area: "منطقه",
  stackedArea: "روی هم رفته",
  normalizedArea: "100% روی هم رفته",

  histogramChart: "هیستوگرام",
  histogramFrequency: "فرکانس",

  combinationChart: "ترکیبی",
  columnLineCombo: "ستون & خط",
  AreaColumnCombo: "منطقه & ستون",

  // Charts
  pivotChartTitle: "نمودار Pivot",
  rangeChartTitle: "نمودار محدوده",
  settings: "تنظیمات",
  data: "داده‌ها",
  format: "فرمت",
  categories: "دسته‌بندی‌ها",
  defaultCategory: "(هیچ)",
  series: "سری‌ها",
  xyValues: "مقادیر X Y",
  paired: "جفت شده",
  axis: "محور",
  navigator: "ناوبر",
  color: "رنگ",
  thickness: "ضخامت",
  xType: "نوع X",
  automatic: "خودکار",

  category: "دسته‌بندی",
  number: "عدد",
  time: "زمان",
  autoRotate: "چرخش خودکار",
  xRotation: "چرخش X",
  yRotation: "چرخش Y",
  ticks: "تیک‌ها",
  width: "عرض",
  height: "ارتفاع",
  length: "طول",
  padding: "فاصله",
  spacing: "فاصله‌گذاری",
  chart: "نمودار",
  title: "عنوان",
  titlePlaceholder: "عنوان نمودار - برای ویرایش دوبار کلیک کنید",
  background: "پس‌زمینه",
  font: "فونت",
  top: "بالا",
  right: "راست",
  bottom: "پایین",
  left: "چپ",
  labels: "برچسب‌ها",
  size: "اندازه",
  minSize: "حداقل اندازه",
  maxSize: "حداکثر اندازه",
  legend: "افسانه",
  position: "موقعیت",
  markerSize: "اندازه نشانگر",
  markerStroke: "ضربه نشانگر",
  markerPadding: "فاصله نشانگر",
  itemSpacing: "فاصله‌گذاری آیتم",
  itemPaddingX: "فاصله آیتم X",
  itemPaddingY: "فاصله آیتم Y",
  layoutHorizontalSpacing: "فاصله‌گذاری افقی",
  layoutVerticalSpacing: "فاصله‌گذاری عمودی",
  strokeWidth: "عرض ضربه",
  lineDash: "خط خطی",
  offset: "انحراف",
  offsets: "انحرافات",
  tooltips: "راهنماها",
  callout: "بیرون زدگی",
  markers: "نشانگرها",
  shadow: "سایه",
  blur: "ماتی",
  xOffset: "انحراف X",
  yOffset: "انحراف Y",
  lineWidth: "عرض خط",
  normal: "عادی",
  bold: "پررنگ",
  italic: "کج",
  boldItalic: "پررنگ و کج",
  predefined: "پیش‌تعریف شده",
  fillOpacity: "شفافیت پر کردن",
  strokeOpacity: "شفافیت خط",
  histogramBinCount: "تعداد سطل هیستوگرام",
  columnGroup: "ستون",
  barGroup: "میله",
  pieGroup: "پای",
  lineGroup: "خط",
  scatterGroup: "X Y (پراکندگی)",
  areaGroup: "منطقه",
  histogramGroup: "هیستوگرام",
  combinationGroup: "ترکیب",
  groupedColumnTooltip: "گروه‌بندی شده",
  stackedColumnTooltip: "روی هم رفته",
  normalizedColumnTooltip: "100% روی هم رفته",
  groupedBarTooltip: "گروه‌بندی شده",
  stackedBarTooltip: "روی هم رفته",
  normalizedBarTooltip: "100% روی هم رفته",
  pieTooltip: "پای",
  doughnutTooltip: "دونات",
  lineTooltip: "خط",
  groupedAreaTooltip: "منطقه",
  stackedAreaTooltip: "روی هم رفته",
  normalizedAreaTooltip: "100% روی هم رفته",
  scatterTooltip: "پراکندگی",
  bubbleTooltip: "حباب",
  histogramTooltip: "هیستوگرام",
  columnLineComboTooltip: "ستون & خط",
  areaColumnComboTooltip: "منطقه & ستون",
  customComboTooltip: "ترکیب سفارشی",
  noDataToChart: "هیچ داده‌ای برای نمودارسازی وجود ندارد.",
  pivotChartRequiresPivotMode: "نمودار Pivot نیازمند حالت Pivot است.",
  chartSettingsToolbarTooltip: "منو",
  chartLinkToolbarTooltip: "مرتبط با Grid",
  chartUnlinkToolbarTooltip: "غیرمرتبط از Grid",
  chartDownloadToolbarTooltip: "دانلود نمودار",
  seriesChartType: "نوع نمودار سری",
  seriesType: "نوع سری",
  secondaryAxis: "محور ثانویه",

  ariaInputEditor: "ویرایشگر ورودی",
  ariaMenuColumn: "برای باز کردن منوی ستون، CTRL ENTER را فشار دهید.",
  ariaRowDeselect: "برای عدم انتخاب این ردیف، SPACE را فشار دهید",
  ariaRowSelectAll: "برای تغییر انتخاب همه ردیف‌ها، Space را فشار دهید",
  ariaRowToggleSelection: "برای تغییر انتخاب ردیف، Space را فشار دهید",
  ariaRowSelect: "برای انتخاب این ردیف، SPACE را فشار دهید",
  ariaSearch: "جستجو",
  ariaSortableColumn: "برای مرتب‌سازی، ENTER را فشار دهید",
  ariaToggleVisibility: "برای تغییر دید، SPACE را فشار دهید",
  ariaToggleCellValue: "برای تغییر مقدار سلول، SPACE را فشار دهید",
  ariaUnchecked: "بررسی نشده",
  ariaVisible: "قابل مشاهده",
  ariaSearchFilterValues: "جستجوی مقادیر فیلتر",
  ariaPageSizeSelectorLabel: "اندازه صفحه",

  // ARIA Labels for Drop Zones
  ariaRowGroupDropZonePanelLabel: "گروه‌های ردیف",
  ariaValuesDropZonePanelLabel: "مقادیر",
  ariaPivotDropZonePanelLabel: "برچسب‌های ستون",
  ariaDropZoneColumnComponentDescription: "برای حذف، DELETE را فشار دهید",
  ariaDropZoneColumnValueItemDescription:
    "برای تغییر نوع تجمع، ENTER را فشار دهید",
  ariaDropZoneColumnGroupItemDescription: "برای مرتب‌سازی، ENTER را فشار دهید",
  ariaDropZoneColumnComponentAggFuncSeparator: " از ",
  ariaDropZoneColumnComponentSortAscending: "صعودی",
  ariaDropZoneColumnComponentSortDescending: "نزولی",

  // ARIA Labels for Dialogs
  ariaLabelColumnMenu: "منوی ستون",
  ariaLabelCellEditor: "ویرایشگر سلول",
  ariaLabelDialog: "دیالوگ",
  ariaLabelSelectField: "انتخاب فیلد",
  ariaLabelRichSelectField: "فیلد انتخاب غنی",
  ariaLabelTooltip: "راهنما",
  ariaLabelContextMenu: "منوی زمینه",
  ariaLabelSubMenu: "زیرمنو",
  ariaLabelAggregationFunction: "تابع تجمع",
  ariaLabelAdvancedFilterAutocomplete: "تکمیل خودکار فیلتر پیشرفته",
  ariaLabelAdvancedFilterBuilderAddField: "افزودن فیلد به ساز فیلتر پیشرفته",
  ariaLabelAdvancedFilterBuilderColumnSelectField:
    "فیلد انتخاب ستون ساز فیلتر پیشرفته",
  ariaLabelAdvancedFilterBuilderOptionSelectField:
    "فیلد انتخاب گزینه ساز فیلتر پیشرفته",
  ariaLabelAdvancedFilterBuilderJoinSelectField:
    "فیلد انتخاب عملگر اتصال ساز فیلتر پیشرفته",

  // ARIA Labels for the Side Bar
  ariaColumnPanelList: "لیست ستون",
  ariaFilterPanelList: "لیست فیلتر",

  // Number Format (Status Bar, Pagination Panel)
  thousandSeparator: ",",
  decimalSeparator: ".",

  // Data types
  true: "صحیح",
  false: "غلط",
  invalidDate: "تاریخ نامعتبر",
  invalidNumber: "عدد نامعتبر",
  january: "ژانویه",
  february: "فوریه",
  march: "مارس",
  april: "آوریل",
  may: "می",
  june: "ژوئن",
  july: "ژوئیه",
  august: "آگوست",
  september: "سپتامبر",
  october: "اکتبر",
  november: "نوامبر",
  december: "دسامبر",
};
